<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- NewPage -->
<html lang="en">
<head>
<!-- Generated by javadoc (1.8.0_161) on Sat Mar 03 00:30:07 GMT 2018 -->
<title>S</title>
<meta name="date" content="2018-03-03">
<link rel="stylesheet" type="text/css" href="../stylesheet.css" title="Style">
<script type="text/javascript" src="../script.js"></script>
</head>
<body>
<script type="text/javascript"><!--
    try {
        if (location.href.indexOf('is-external=true') == -1) {
            parent.document.title="S";
        }
    }
    catch(err) {
    }
//-->
var methods = {"i0":9,"i1":9,"i2":9,"i3":9,"i4":9,"i5":9,"i6":9,"i7":9,"i8":9,"i9":9,"i10":9,"i11":9,"i12":9,"i13":9,"i14":9,"i15":9,"i16":9,"i17":9,"i18":9,"i19":9,"i20":9,"i21":9};
var tabs = {65535:["t0","All Methods"],1:["t1","Static Methods"],8:["t4","Concrete Methods"]};
var altColor = "altColor";
var rowColor = "rowColor";
var tableTab = "tableTab";
var activeTableTab = "activeTableTab";
</script>
<noscript>
<div>JavaScript is disabled on your browser.</div>
</noscript>
<!-- ========= START OF TOP NAVBAR ======= -->
<div class="topNav"><a name="navbar.top">
<!--   -->
</a>
<div class="skipNav"><a href="#skip.navbar.top" title="Skip navigation links">Skip navigation links</a></div>
<a name="navbar.top.firstrow">
<!--   -->
</a>
<ul class="navList" title="Navigation">
<li><a href="../util/package-summary.html">Package</a></li>
<li class="navBarCell1Rev">Class</li>
<li><a href="class-use/S.html">Use</a></li>
<li><a href="package-tree.html">Tree</a></li>
<li><a href="../deprecated-list.html">Deprecated</a></li>
<li><a href="../index-files/index-1.html">Index</a></li>
<li><a href="../help-doc.html">Help</a></li>
</ul>
</div>
<div class="subNav">
<ul class="navList">
<li>Prev&nbsp;Class</li>
<li><a href="../util/Utils2.html" title="class in util"><span class="typeNameLink">Next&nbsp;Class</span></a></li>
</ul>
<ul class="navList">
<li><a href="../index.html?util/S.html" target="_top">Frames</a></li>
<li><a href="S.html" target="_top">No&nbsp;Frames</a></li>
</ul>
<ul class="navList" id="allclasses_navbar_top">
<li><a href="../allclasses-noframe.html">All&nbsp;Classes</a></li>
</ul>
<div>
<script type="text/javascript"><!--
  allClassesLink = document.getElementById("allclasses_navbar_top");
  if(window==top) {
    allClassesLink.style.display = "block";
  }
  else {
    allClassesLink.style.display = "none";
  }
  //-->
</script>
</div>
<div>
<ul class="subNavList">
<li>Summary:&nbsp;</li>
<li>Nested&nbsp;|&nbsp;</li>
<li>Field&nbsp;|&nbsp;</li>
<li><a href="#constructor.summary">Constr</a>&nbsp;|&nbsp;</li>
<li><a href="#method.summary">Method</a></li>
</ul>
<ul class="subNavList">
<li>Detail:&nbsp;</li>
<li>Field&nbsp;|&nbsp;</li>
<li><a href="#constructor.detail">Constr</a>&nbsp;|&nbsp;</li>
<li><a href="#method.detail">Method</a></li>
</ul>
</div>
<a name="skip.navbar.top">
<!--   -->
</a></div>
<!-- ========= END OF TOP NAVBAR ========= -->
<!-- ======== START OF CLASS DATA ======== -->
<div class="header">
<div class="subTitle">util</div>
<h2 title="Class S" class="title">Class S</h2>
</div>
<div class="contentContainer">
<ul class="inheritance">
<li>java.lang.Object</li>
<li>
<ul class="inheritance">
<li>util.S</li>
</ul>
</li>
</ul>
<div class="description">
<ul class="blockList">
<li class="blockList">
<hr>
<br>
<pre>public class <span class="typeNameLabel">S</span>
extends java.lang.Object</pre>
</li>
</ul>
</div>
<div class="summary">
<ul class="blockList">
<li class="blockList">
<!-- ======== CONSTRUCTOR SUMMARY ======== -->
<ul class="blockList">
<li class="blockList"><a name="constructor.summary">
<!--   -->
</a>
<h3>Constructor Summary</h3>
<table class="memberSummary" border="0" cellpadding="3" cellspacing="0" summary="Constructor Summary table, listing constructors, and an explanation">
<caption><span>Constructors</span><span class="tabEnd">&nbsp;</span></caption>
<tr>
<th class="colOne" scope="col">Constructor and Description</th>
</tr>
<tr class="altColor">
<td class="colOne"><code><span class="memberNameLink"><a href="../util/S.html#S--">S</a></span>()</code>&nbsp;</td>
</tr>
</table>
</li>
</ul>
<!-- ========== METHOD SUMMARY =========== -->
<ul class="blockList">
<li class="blockList"><a name="method.summary">
<!--   -->
</a>
<h3>Method Summary</h3>
<table class="memberSummary" border="0" cellpadding="3" cellspacing="0" summary="Method Summary table, listing methods, and an explanation">
<caption><span id="t0" class="activeTableTab"><span>All Methods</span><span class="tabEnd">&nbsp;</span></span><span id="t1" class="tableTab"><span><a href="javascript:show(1);">Static Methods</a></span><span class="tabEnd">&nbsp;</span></span><span id="t4" class="tableTab"><span><a href="javascript:show(8);">Concrete Methods</a></span><span class="tabEnd">&nbsp;</span></span></caption>
<tr>
<th class="colFirst" scope="col">Modifier and Type</th>
<th class="colLast" scope="col">Method and Description</th>
</tr>
<tr id="i0" class="altColor">
<td class="colFirst"><code>static void</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../util/S.html#ep-java.lang.String-">ep</a></span>(java.lang.String&nbsp;text)</code>&nbsp;</td>
</tr>
<tr id="i1" class="rowColor">
<td class="colFirst"><code>static void</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../util/S.html#epl-java.lang.String-">epl</a></span>(java.lang.String&nbsp;text)</code>&nbsp;</td>
</tr>
<tr id="i2" class="altColor">
<td class="colFirst"><code>static void</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../util/S.html#exit--">exit</a></span>()</code>&nbsp;</td>
</tr>
<tr id="i3" class="rowColor">
<td class="colFirst"><code>static void</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../util/S.html#nt--">nt</a></span>()</code>&nbsp;</td>
</tr>
<tr id="i4" class="altColor">
<td class="colFirst"><code>static void</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../util/S.html#p-boolean-">p</a></span>(boolean&nbsp;isTrue)</code>&nbsp;</td>
</tr>
<tr id="i5" class="rowColor">
<td class="colFirst"><code>static void</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../util/S.html#p-byte:A-">p</a></span>(byte[]&nbsp;numbers)</code>&nbsp;</td>
</tr>
<tr id="i6" class="altColor">
<td class="colFirst"><code>static void</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../util/S.html#p-char:A-">p</a></span>(char[]&nbsp;numbers)</code>&nbsp;</td>
</tr>
<tr id="i7" class="rowColor">
<td class="colFirst"><code>static void</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../util/S.html#p-int-">p</a></span>(int&nbsp;number)</code>&nbsp;</td>
</tr>
<tr id="i8" class="altColor">
<td class="colFirst"><code>static void</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../util/S.html#p-int:A-">p</a></span>(int[]&nbsp;numbers)</code>&nbsp;</td>
</tr>
<tr id="i9" class="rowColor">
<td class="colFirst"><code>static void</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../util/S.html#p-long-">p</a></span>(long&nbsp;number)</code>&nbsp;</td>
</tr>
<tr id="i10" class="altColor">
<td class="colFirst"><code>static void</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../util/S.html#p-long:A-">p</a></span>(long[]&nbsp;numbers)</code>&nbsp;</td>
</tr>
<tr id="i11" class="rowColor">
<td class="colFirst"><code>static void</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../util/S.html#p-java.lang.String-">p</a></span>(java.lang.String&nbsp;text)</code>&nbsp;</td>
</tr>
<tr id="i12" class="altColor">
<td class="colFirst"><code>static void</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../util/S.html#pl--">pl</a></span>()</code>&nbsp;</td>
</tr>
<tr id="i13" class="rowColor">
<td class="colFirst"><code>static void</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../util/S.html#pl-boolean-">pl</a></span>(boolean&nbsp;isTrue)</code>&nbsp;</td>
</tr>
<tr id="i14" class="altColor">
<td class="colFirst"><code>static void</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../util/S.html#pl-byte:A-">pl</a></span>(byte[]&nbsp;numbers)</code>&nbsp;</td>
</tr>
<tr id="i15" class="rowColor">
<td class="colFirst"><code>static void</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../util/S.html#pl-char:A-">pl</a></span>(char[]&nbsp;numbers)</code>&nbsp;</td>
</tr>
<tr id="i16" class="altColor">
<td class="colFirst"><code>static void</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../util/S.html#pl-int-">pl</a></span>(int&nbsp;number)</code>&nbsp;</td>
</tr>
<tr id="i17" class="rowColor">
<td class="colFirst"><code>static void</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../util/S.html#pl-int:A-">pl</a></span>(int[]&nbsp;numbers)</code>&nbsp;</td>
</tr>
<tr id="i18" class="altColor">
<td class="colFirst"><code>static void</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../util/S.html#pl-long-">pl</a></span>(long&nbsp;number)</code>&nbsp;</td>
</tr>
<tr id="i19" class="rowColor">
<td class="colFirst"><code>static void</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../util/S.html#pl-long:A-">pl</a></span>(long[]&nbsp;numbers)</code>&nbsp;</td>
</tr>
<tr id="i20" class="altColor">
<td class="colFirst"><code>static void</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../util/S.html#pl-java.lang.String-">pl</a></span>(java.lang.String&nbsp;text)</code>&nbsp;</td>
</tr>
<tr id="i21" class="rowColor">
<td class="colFirst"><code>static void</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../util/S.html#pl-java.lang.String:A-">pl</a></span>(java.lang.String[]&nbsp;text)</code>&nbsp;</td>
</tr>
</table>
<ul class="blockList">
<li class="blockList"><a name="methods.inherited.from.class.java.lang.Object">
<!--   -->
</a>
<h3>Methods inherited from class&nbsp;java.lang.Object</h3>
<code>equals, getClass, hashCode, notify, notifyAll, toString, wait, wait, wait</code></li>
</ul>
</li>
</ul>
</li>
</ul>
</div>
<div class="details">
<ul class="blockList">
<li class="blockList">
<!-- ========= CONSTRUCTOR DETAIL ======== -->
<ul class="blockList">
<li class="blockList"><a name="constructor.detail">
<!--   -->
</a>
<h3>Constructor Detail</h3>
<a name="S--">
<!--   -->
</a>
<ul class="blockListLast">
<li class="blockList">
<h4>S</h4>
<pre>public&nbsp;S()</pre>
</li>
</ul>
</li>
</ul>
<!-- ============ METHOD DETAIL ========== -->
<ul class="blockList">
<li class="blockList"><a name="method.detail">
<!--   -->
</a>
<h3>Method Detail</h3>
<a name="exit--">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>exit</h4>
<pre>public static&nbsp;void&nbsp;exit()</pre>
</li>
</ul>
<a name="p-java.lang.String-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>p</h4>
<pre>public static&nbsp;void&nbsp;p(java.lang.String&nbsp;text)</pre>
</li>
</ul>
<a name="ep-java.lang.String-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>ep</h4>
<pre>public static&nbsp;void&nbsp;ep(java.lang.String&nbsp;text)</pre>
</li>
</ul>
<a name="p-int-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>p</h4>
<pre>public static&nbsp;void&nbsp;p(int&nbsp;number)</pre>
</li>
</ul>
<a name="p-long-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>p</h4>
<pre>public static&nbsp;void&nbsp;p(long&nbsp;number)</pre>
</li>
</ul>
<a name="p-boolean-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>p</h4>
<pre>public static&nbsp;void&nbsp;p(boolean&nbsp;isTrue)</pre>
</li>
</ul>
<a name="p-long:A-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>p</h4>
<pre>public static&nbsp;void&nbsp;p(long[]&nbsp;numbers)</pre>
</li>
</ul>
<a name="p-int:A-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>p</h4>
<pre>public static&nbsp;void&nbsp;p(int[]&nbsp;numbers)</pre>
</li>
</ul>
<a name="p-char:A-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>p</h4>
<pre>public static&nbsp;void&nbsp;p(char[]&nbsp;numbers)</pre>
</li>
</ul>
<a name="p-byte:A-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>p</h4>
<pre>public static&nbsp;void&nbsp;p(byte[]&nbsp;numbers)</pre>
</li>
</ul>
<a name="pl-java.lang.String:A-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>pl</h4>
<pre>public static&nbsp;void&nbsp;pl(java.lang.String[]&nbsp;text)</pre>
</li>
</ul>
<a name="pl-java.lang.String-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>pl</h4>
<pre>public static&nbsp;void&nbsp;pl(java.lang.String&nbsp;text)</pre>
</li>
</ul>
<a name="epl-java.lang.String-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>epl</h4>
<pre>public static&nbsp;void&nbsp;epl(java.lang.String&nbsp;text)</pre>
</li>
</ul>
<a name="pl-int-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>pl</h4>
<pre>public static&nbsp;void&nbsp;pl(int&nbsp;number)</pre>
</li>
</ul>
<a name="pl-long-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>pl</h4>
<pre>public static&nbsp;void&nbsp;pl(long&nbsp;number)</pre>
</li>
</ul>
<a name="pl--">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>pl</h4>
<pre>public static&nbsp;void&nbsp;pl()</pre>
</li>
</ul>
<a name="pl-boolean-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>pl</h4>
<pre>public static&nbsp;void&nbsp;pl(boolean&nbsp;isTrue)</pre>
</li>
</ul>
<a name="pl-long:A-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>pl</h4>
<pre>public static&nbsp;void&nbsp;pl(long[]&nbsp;numbers)</pre>
</li>
</ul>
<a name="pl-int:A-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>pl</h4>
<pre>public static&nbsp;void&nbsp;pl(int[]&nbsp;numbers)</pre>
</li>
</ul>
<a name="pl-char:A-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>pl</h4>
<pre>public static&nbsp;void&nbsp;pl(char[]&nbsp;numbers)</pre>
</li>
</ul>
<a name="pl-byte:A-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>pl</h4>
<pre>public static&nbsp;void&nbsp;pl(byte[]&nbsp;numbers)</pre>
</li>
</ul>
<a name="nt--">
<!--   -->
</a>
<ul class="blockListLast">
<li class="blockList">
<h4>nt</h4>
<pre>public static&nbsp;void&nbsp;nt()</pre>
</li>
</ul>
</li>
</ul>
</li>
</ul>
</div>
</div>
<!-- ========= END OF CLASS DATA ========= -->
<!-- ======= START OF BOTTOM NAVBAR ====== -->
<div class="bottomNav"><a name="navbar.bottom">
<!--   -->
</a>
<div class="skipNav"><a href="#skip.navbar.bottom" title="Skip navigation links">Skip navigation links</a></div>
<a name="navbar.bottom.firstrow">
<!--   -->
</a>
<ul class="navList" title="Navigation">
<li><a href="../util/package-summary.html">Package</a></li>
<li class="navBarCell1Rev">Class</li>
<li><a href="class-use/S.html">Use</a></li>
<li><a href="package-tree.html">Tree</a></li>
<li><a href="../deprecated-list.html">Deprecated</a></li>
<li><a href="../index-files/index-1.html">Index</a></li>
<li><a href="../help-doc.html">Help</a></li>
</ul>
</div>
<div class="subNav">
<ul class="navList">
<li>Prev&nbsp;Class</li>
<li><a href="../util/Utils2.html" title="class in util"><span class="typeNameLink">Next&nbsp;Class</span></a></li>
</ul>
<ul class="navList">
<li><a href="../index.html?util/S.html" target="_top">Frames</a></li>
<li><a href="S.html" target="_top">No&nbsp;Frames</a></li>
</ul>
<ul class="navList" id="allclasses_navbar_bottom">
<li><a href="../allclasses-noframe.html">All&nbsp;Classes</a></li>
</ul>
<div>
<script type="text/javascript"><!--
  allClassesLink = document.getElementById("allclasses_navbar_bottom");
  if(window==top) {
    allClassesLink.style.display = "block";
  }
  else {
    allClassesLink.style.display = "none";
  }
  //-->
</script>
</div>
<div>
<ul class="subNavList">
<li>Summary:&nbsp;</li>
<li>Nested&nbsp;|&nbsp;</li>
<li>Field&nbsp;|&nbsp;</li>
<li><a href="#constructor.summary">Constr</a>&nbsp;|&nbsp;</li>
<li><a href="#method.summary">Method</a></li>
</ul>
<ul class="subNavList">
<li>Detail:&nbsp;</li>
<li>Field&nbsp;|&nbsp;</li>
<li><a href="#constructor.detail">Constr</a>&nbsp;|&nbsp;</li>
<li><a href="#method.detail">Method</a></li>
</ul>
</div>
<a name="skip.navbar.bottom">
<!--   -->
</a></div>
<!-- ======== END OF BOTTOM NAVBAR ======= -->
</body>
</html>
